services:
  - type: web
    name: tra-cuu-tbyt
    runtime: python
    region: singapore
    plan: free
    buildCommand: "echo khong-can-cai-gi"
    startCommand: "python3 app.py"
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PYTHON_VERSION
        value: 3.12.7
